/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthedRouteRouteImport } from './routes/_unauthed/route'
import { Route as CreateProfileRouteRouteImport } from './routes/_createProfile/route'
import { Route as CompleteRouteRouteImport } from './routes/_complete/route'
import { Route as UnauthedIndexRouteImport } from './routes/_unauthed/index'
import { Route as UnauthedAuthRouteImport } from './routes/_unauthed/auth'
import { Route as CompleteLobbiesRouteImport } from './routes/_complete/lobbies'
import { Route as CreateProfileAuthCreateProfileRouteImport } from './routes/_createProfile/auth.create-profile'
import { Route as CompleteProfileMeRouteImport } from './routes/_complete/profile.me'

const UnauthedRouteRoute = UnauthedRouteRouteImport.update({
  id: '/_unauthed',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProfileRouteRoute = CreateProfileRouteRouteImport.update({
  id: '/_createProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRouteRoute = CompleteRouteRouteImport.update({
  id: '/_complete',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthedIndexRoute = UnauthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnauthedRouteRoute,
} as any)
const UnauthedAuthRoute = UnauthedAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => UnauthedRouteRoute,
} as any)
const CompleteLobbiesRoute = CompleteLobbiesRouteImport.update({
  id: '/lobbies',
  path: '/lobbies',
  getParentRoute: () => CompleteRouteRoute,
} as any)
const CreateProfileAuthCreateProfileRoute =
  CreateProfileAuthCreateProfileRouteImport.update({
    id: '/auth/create-profile',
    path: '/auth/create-profile',
    getParentRoute: () => CreateProfileRouteRoute,
  } as any)
const CompleteProfileMeRoute = CompleteProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => CompleteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/lobbies': typeof CompleteLobbiesRoute
  '/auth': typeof UnauthedAuthRoute
  '/': typeof UnauthedIndexRoute
  '/profile/me': typeof CompleteProfileMeRoute
  '/auth/create-profile': typeof CreateProfileAuthCreateProfileRoute
}
export interface FileRoutesByTo {
  '/lobbies': typeof CompleteLobbiesRoute
  '/auth': typeof UnauthedAuthRoute
  '/': typeof UnauthedIndexRoute
  '/profile/me': typeof CompleteProfileMeRoute
  '/auth/create-profile': typeof CreateProfileAuthCreateProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_complete': typeof CompleteRouteRouteWithChildren
  '/_createProfile': typeof CreateProfileRouteRouteWithChildren
  '/_unauthed': typeof UnauthedRouteRouteWithChildren
  '/_complete/lobbies': typeof CompleteLobbiesRoute
  '/_unauthed/auth': typeof UnauthedAuthRoute
  '/_unauthed/': typeof UnauthedIndexRoute
  '/_complete/profile/me': typeof CompleteProfileMeRoute
  '/_createProfile/auth/create-profile': typeof CreateProfileAuthCreateProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/lobbies' | '/auth' | '/' | '/profile/me' | '/auth/create-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/lobbies' | '/auth' | '/' | '/profile/me' | '/auth/create-profile'
  id:
    | '__root__'
    | '/_complete'
    | '/_createProfile'
    | '/_unauthed'
    | '/_complete/lobbies'
    | '/_unauthed/auth'
    | '/_unauthed/'
    | '/_complete/profile/me'
    | '/_createProfile/auth/create-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CompleteRouteRoute: typeof CompleteRouteRouteWithChildren
  CreateProfileRouteRoute: typeof CreateProfileRouteRouteWithChildren
  UnauthedRouteRoute: typeof UnauthedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthed': {
      id: '/_unauthed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_createProfile': {
      id: '/_createProfile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CreateProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_complete': {
      id: '/_complete'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CompleteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthed/': {
      id: '/_unauthed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthedIndexRouteImport
      parentRoute: typeof UnauthedRouteRoute
    }
    '/_unauthed/auth': {
      id: '/_unauthed/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof UnauthedAuthRouteImport
      parentRoute: typeof UnauthedRouteRoute
    }
    '/_complete/lobbies': {
      id: '/_complete/lobbies'
      path: '/lobbies'
      fullPath: '/lobbies'
      preLoaderRoute: typeof CompleteLobbiesRouteImport
      parentRoute: typeof CompleteRouteRoute
    }
    '/_createProfile/auth/create-profile': {
      id: '/_createProfile/auth/create-profile'
      path: '/auth/create-profile'
      fullPath: '/auth/create-profile'
      preLoaderRoute: typeof CreateProfileAuthCreateProfileRouteImport
      parentRoute: typeof CreateProfileRouteRoute
    }
    '/_complete/profile/me': {
      id: '/_complete/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof CompleteProfileMeRouteImport
      parentRoute: typeof CompleteRouteRoute
    }
  }
}

interface CompleteRouteRouteChildren {
  CompleteLobbiesRoute: typeof CompleteLobbiesRoute
  CompleteProfileMeRoute: typeof CompleteProfileMeRoute
}

const CompleteRouteRouteChildren: CompleteRouteRouteChildren = {
  CompleteLobbiesRoute: CompleteLobbiesRoute,
  CompleteProfileMeRoute: CompleteProfileMeRoute,
}

const CompleteRouteRouteWithChildren = CompleteRouteRoute._addFileChildren(
  CompleteRouteRouteChildren,
)

interface CreateProfileRouteRouteChildren {
  CreateProfileAuthCreateProfileRoute: typeof CreateProfileAuthCreateProfileRoute
}

const CreateProfileRouteRouteChildren: CreateProfileRouteRouteChildren = {
  CreateProfileAuthCreateProfileRoute: CreateProfileAuthCreateProfileRoute,
}

const CreateProfileRouteRouteWithChildren =
  CreateProfileRouteRoute._addFileChildren(CreateProfileRouteRouteChildren)

interface UnauthedRouteRouteChildren {
  UnauthedAuthRoute: typeof UnauthedAuthRoute
  UnauthedIndexRoute: typeof UnauthedIndexRoute
}

const UnauthedRouteRouteChildren: UnauthedRouteRouteChildren = {
  UnauthedAuthRoute: UnauthedAuthRoute,
  UnauthedIndexRoute: UnauthedIndexRoute,
}

const UnauthedRouteRouteWithChildren = UnauthedRouteRoute._addFileChildren(
  UnauthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CompleteRouteRoute: CompleteRouteRouteWithChildren,
  CreateProfileRouteRoute: CreateProfileRouteRouteWithChildren,
  UnauthedRouteRoute: UnauthedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
