/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCreateProfileRouteImport } from './routes/auth/create-profile'
import { Route as AuthProfileRouteRouteImport } from './routes/_auth/_profile/route'
import { Route as AuthProfileLobbyRouteRouteImport } from './routes/_auth/_profile/_lobby/route'
import { Route as AuthProfileProfileMeRouteImport } from './routes/_auth/_profile/profile.me'
import { Route as AuthProfileLobbyLobbyRouteImport } from './routes/_auth/_profile/_lobby/lobby'
import { Route as AuthProfileLobbyLeaveOldLobbyRouteImport } from './routes/_auth/_profile/_lobby/leave-old-lobby'
import { Route as AuthProfileLobbyHomeRouteImport } from './routes/_auth/_profile/_lobby/home'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateProfileRoute = AuthCreateProfileRouteImport.update({
  id: '/auth/create-profile',
  path: '/auth/create-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRouteRoute = AuthProfileRouteRouteImport.update({
  id: '/_profile',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileLobbyRouteRoute = AuthProfileLobbyRouteRouteImport.update({
  id: '/_lobby',
  getParentRoute: () => AuthProfileRouteRoute,
} as any)
const AuthProfileProfileMeRoute = AuthProfileProfileMeRouteImport.update({
  id: '/profile/me',
  path: '/profile/me',
  getParentRoute: () => AuthProfileRouteRoute,
} as any)
const AuthProfileLobbyLobbyRoute = AuthProfileLobbyLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => AuthProfileLobbyRouteRoute,
} as any)
const AuthProfileLobbyLeaveOldLobbyRoute =
  AuthProfileLobbyLeaveOldLobbyRouteImport.update({
    id: '/leave-old-lobby',
    path: '/leave-old-lobby',
    getParentRoute: () => AuthProfileLobbyRouteRoute,
  } as any)
const AuthProfileLobbyHomeRoute = AuthProfileLobbyHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthProfileLobbyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/create-profile': typeof AuthCreateProfileRoute
  '/auth': typeof AuthIndexRoute
  '/home': typeof AuthProfileLobbyHomeRoute
  '/leave-old-lobby': typeof AuthProfileLobbyLeaveOldLobbyRoute
  '/lobby': typeof AuthProfileLobbyLobbyRoute
  '/profile/me': typeof AuthProfileProfileMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/create-profile': typeof AuthCreateProfileRoute
  '/auth': typeof AuthIndexRoute
  '/home': typeof AuthProfileLobbyHomeRoute
  '/leave-old-lobby': typeof AuthProfileLobbyLeaveOldLobbyRoute
  '/lobby': typeof AuthProfileLobbyLobbyRoute
  '/profile/me': typeof AuthProfileProfileMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/_profile': typeof AuthProfileRouteRouteWithChildren
  '/auth/create-profile': typeof AuthCreateProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/_auth/_profile/_lobby': typeof AuthProfileLobbyRouteRouteWithChildren
  '/_auth/_profile/_lobby/home': typeof AuthProfileLobbyHomeRoute
  '/_auth/_profile/_lobby/leave-old-lobby': typeof AuthProfileLobbyLeaveOldLobbyRoute
  '/_auth/_profile/_lobby/lobby': typeof AuthProfileLobbyLobbyRoute
  '/_auth/_profile/profile/me': typeof AuthProfileProfileMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/create-profile'
    | '/auth'
    | '/home'
    | '/leave-old-lobby'
    | '/lobby'
    | '/profile/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/create-profile'
    | '/auth'
    | '/home'
    | '/leave-old-lobby'
    | '/lobby'
    | '/profile/me'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/_profile'
    | '/auth/create-profile'
    | '/auth/'
    | '/_auth/_profile/_lobby'
    | '/_auth/_profile/_lobby/home'
    | '/_auth/_profile/_lobby/leave-old-lobby'
    | '/_auth/_profile/_lobby/lobby'
    | '/_auth/_profile/profile/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthCreateProfileRoute: typeof AuthCreateProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-profile': {
      id: '/auth/create-profile'
      path: '/auth/create-profile'
      fullPath: '/auth/create-profile'
      preLoaderRoute: typeof AuthCreateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_profile': {
      id: '/_auth/_profile'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthProfileRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_profile/_lobby': {
      id: '/_auth/_profile/_lobby'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthProfileLobbyRouteRouteImport
      parentRoute: typeof AuthProfileRouteRoute
    }
    '/_auth/_profile/profile/me': {
      id: '/_auth/_profile/profile/me'
      path: '/profile/me'
      fullPath: '/profile/me'
      preLoaderRoute: typeof AuthProfileProfileMeRouteImport
      parentRoute: typeof AuthProfileRouteRoute
    }
    '/_auth/_profile/_lobby/lobby': {
      id: '/_auth/_profile/_lobby/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof AuthProfileLobbyLobbyRouteImport
      parentRoute: typeof AuthProfileLobbyRouteRoute
    }
    '/_auth/_profile/_lobby/leave-old-lobby': {
      id: '/_auth/_profile/_lobby/leave-old-lobby'
      path: '/leave-old-lobby'
      fullPath: '/leave-old-lobby'
      preLoaderRoute: typeof AuthProfileLobbyLeaveOldLobbyRouteImport
      parentRoute: typeof AuthProfileLobbyRouteRoute
    }
    '/_auth/_profile/_lobby/home': {
      id: '/_auth/_profile/_lobby/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthProfileLobbyHomeRouteImport
      parentRoute: typeof AuthProfileLobbyRouteRoute
    }
  }
}

interface AuthProfileLobbyRouteRouteChildren {
  AuthProfileLobbyHomeRoute: typeof AuthProfileLobbyHomeRoute
  AuthProfileLobbyLeaveOldLobbyRoute: typeof AuthProfileLobbyLeaveOldLobbyRoute
  AuthProfileLobbyLobbyRoute: typeof AuthProfileLobbyLobbyRoute
}

const AuthProfileLobbyRouteRouteChildren: AuthProfileLobbyRouteRouteChildren = {
  AuthProfileLobbyHomeRoute: AuthProfileLobbyHomeRoute,
  AuthProfileLobbyLeaveOldLobbyRoute: AuthProfileLobbyLeaveOldLobbyRoute,
  AuthProfileLobbyLobbyRoute: AuthProfileLobbyLobbyRoute,
}

const AuthProfileLobbyRouteRouteWithChildren =
  AuthProfileLobbyRouteRoute._addFileChildren(
    AuthProfileLobbyRouteRouteChildren,
  )

interface AuthProfileRouteRouteChildren {
  AuthProfileLobbyRouteRoute: typeof AuthProfileLobbyRouteRouteWithChildren
  AuthProfileProfileMeRoute: typeof AuthProfileProfileMeRoute
}

const AuthProfileRouteRouteChildren: AuthProfileRouteRouteChildren = {
  AuthProfileLobbyRouteRoute: AuthProfileLobbyRouteRouteWithChildren,
  AuthProfileProfileMeRoute: AuthProfileProfileMeRoute,
}

const AuthProfileRouteRouteWithChildren =
  AuthProfileRouteRoute._addFileChildren(AuthProfileRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthProfileRouteRoute: typeof AuthProfileRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthProfileRouteRoute: AuthProfileRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthCreateProfileRoute: AuthCreateProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
