$schema = "https://railway.com/railway.schema.json"

[build]
# Optional: which files should trigger a rebuild
watchPatterns = [
  "/backend/**",
  "/game/**"
]

# run on the build host to ensure the lock is valid for Railway's platform
installCommand = "uv lock && uv sync --frozen --no-dev --no-install-project"

# final build step: install the project (no editing / no dev deps)
buildCommand = "uv sync --frozen --no-dev --no-editable"

[deploy]
# preDeployCommand can be used, but note it runs *after* build and before deployment
# preDeployCommand = ["your migrate script or other commands"]

# start the app (Railway will substitute $PORT)
startCommand = "uv run --package backend uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
