name: auction-chess-api
region: nyc

services:
  - name: api
    # Path to server directory in monorepo
    source_dir: /server

    # Use Dockerfile for deployment
    dockerfile_path: server/Dockerfile

    # GitHub integration (update with your repo details)
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/auction-chess

    # Build configuration
    build_command: echo "Building with Docker"

    # Environment variables (set these in DO dashboard or via doctl)
    envs:
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "8000"
        scope: RUN_TIME

    # HTTP configuration
    http_port: 8000

    # Health check
    health_check:
      http_path: /api
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # Routes
    routes:
      - path: /api
