
  create table "public"."lobbies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text not null
      );


alter table "public"."lobbies" enable row level security;

CREATE UNIQUE INDEX lobbies_pkey ON public.lobbies USING btree (id);

alter table "public"."lobbies" add constraint "lobbies_pkey" PRIMARY KEY using index "lobbies_pkey";

grant delete on table "public"."lobbies" to "anon";

grant insert on table "public"."lobbies" to "anon";

grant references on table "public"."lobbies" to "anon";

grant select on table "public"."lobbies" to "anon";

grant trigger on table "public"."lobbies" to "anon";

grant truncate on table "public"."lobbies" to "anon";

grant update on table "public"."lobbies" to "anon";

grant delete on table "public"."lobbies" to "authenticated";

grant insert on table "public"."lobbies" to "authenticated";

grant references on table "public"."lobbies" to "authenticated";

grant select on table "public"."lobbies" to "authenticated";

grant trigger on table "public"."lobbies" to "authenticated";

grant truncate on table "public"."lobbies" to "authenticated";

grant update on table "public"."lobbies" to "authenticated";

grant delete on table "public"."lobbies" to "service_role";

grant insert on table "public"."lobbies" to "service_role";

grant references on table "public"."lobbies" to "service_role";

grant select on table "public"."lobbies" to "service_role";

grant trigger on table "public"."lobbies" to "service_role";

grant truncate on table "public"."lobbies" to "service_role";

grant update on table "public"."lobbies" to "service_role";


